ユーザー登録機能を実装する
yuta-ushijima/qiita_clone pull request #11
Opened 2018-08-07 10:19 UTC by yuta-ushijima

## 概要
ユーザー登録機能を実装する

## 関連するIssue
#10 

## 工数
ここまでにかかった時間: 4.0H(8/7)

2018-08-07 10:24 UTC, yuta-ushijima commented
とりあえずCRUD処理とそれに伴うspecを作成しました。

ここまでで一旦レビューいただけると！

登録画面なんですけど、フロント用のプロジェクトを別途作成した方がいいですかね？

2018-08-07 10:49 UTC, mc-chinju commented
> ここまでで一旦レビューいただけると！

了解ですー。仕事終わり次第見ますね。

> 登録画面なんですけど、フロント用のプロジェクトを別途作成した方がいいですかね？

一緒でいいんじゃないでしょうか！（そこまで大きなプロジェクトじゃなければ一つにすることが多いです）

2018-08-07 11:47 UTC, yuta-ushijima commented
>一緒でいいんじゃないでしょうか！（そこまで大きなプロジェクトじゃなければ一つにすることが多いです）

なるほど！その場合って、Railsプロジェクト内に`frontend`ディレクトリみたいなの作って、そこでvueの設定などを構築していけばいいですかね？

2018-08-07 11:59 UTC, mc-chinju commented
webpack=vue だと全部自動でやってくれませんでしたっけ？

Rails が準備してくれるものが気に入らない場合は独自で入れればいいかなーくらいでした。またはあとから追加する場合。

2018-08-07 12:26 UTC, yuta-ushijima commented
>webpack=vue だと全部自動でやってくれませんでしたっけ？
vue側の設定は基本やってくれる認識です！

>Rails が準備してくれるものが気に入らない場合は独自で入れればいい
なるほど！となるとapiモードにしているので、Rails側の設定は独自でやらないとですよね><

2018-08-07 12:28 UTC, mc-chinju commented
client 側では Rails が準備するAPIを叩くようにしてあげるだけですねー。

Railsは単なるAPIサーバーなので特に変わった設定はいらないはず。

2018-08-07 12:39 UTC, yuta-ushijima commented
>client 側では Rails が準備するAPIを叩くようにしてあげるだけ

ふむふむ。

>Railsは単なるAPIサーバーなので特に変わった設定はいらない

application.html.erbとか設定する必要があるのかなと思ったんですけど、それもいらない感じですか？

2018-08-07 12:50 UTC, mc-chinju commented
> application.html.erbとか設定する必要があるのかなと思ったんですけど、それもいらない感じですか？

Rails 側で html 返す必要がないので不要だと思います！

2018-08-07 12:53 UTC, mc-chinju commented on config/routes.rb
> +  namespace :api, { format: 'json'} do
このままでももちろんいいのですが、namespace で `v1` 切ってもいいかもですね。

2018-08-07 12:54 UTC, mc-chinju commented on db/migrate/20180807053722_create_users.rb
> +      t.string :password_confirm
ログイン機能は独自で実装する予定ですか？
`devise` などを使う場合は、まだ password 系入れなくていいと思いますよ。
あと、 `null: false` とか入れる必要はないですか？ model で validation 切るのはもちろんですが、DB 側でも可能な限り適切な制限入れたほうがいいかと思いますー

2018-08-07 12:57 UTC, mc-chinju commented on spec/models/user_spec.rb
> +        password_confirm: "hogehoge")
ここは factory_bot で作りましょうw

2018-08-07 12:58 UTC, mc-chinju commented on spec/controllers/api/users_controller_spec.rb
> +    let(:user) { FactoryBot.create(:user)}
あえて明示しているのであればいいのですが、`FactoryBot` のメソッドは、直で呼べます。

```rb
let(:user) { create(:user) }
```

で十分なのです。

2018-08-07 12:58 UTC, yuta-ushijima commented on spec/models/user_spec.rb
> +        password_confirm: "hogehoge")
>ここは factory_bot で作りましょうw

ちゃんとコントローラー側でFactoryBot使っているのに、なにしてるんですかねw
修正します><

2018-08-07 13:02 UTC, yuta-ushijima commented on db/migrate/20180807053722_create_users.rb
> +      t.string :password_confirm
>devise などを使う場合は、まだ password 系入れなくていいと思いますよ。
!!!deviseをgemfileで入れているのに、すっかり抜けてました。。
言われてみればそうですよね。。

>null: false とか入れる必要
DB 側でも可能な限り適切な制限入れたほうがいい

モデル側のvalidation入れる時に、一緒にやろうかなーと思ってましたが、
最初に設定するべきでしたね。。

2018-08-07 13:05 UTC, mc-chinju commented on app/controllers/api/users_controller.rb
> +    end
このあたり、active_model_serializer に差し替えるのは後の PR でって感じですかね？

2018-08-07 13:09 UTC, mc-chinju commented on app/controllers/api/users_controller.rb
> +    if @user.save
あんまり `save` は使わないほうがいいですよー。boolean しか返さないので。
validation に引っかかったら Error を返す `save!` を使うのが基本です！

2018-08-07 13:12 UTC, yuta-ushijima commented on app/controllers/api/users_controller.rb
> +    end
今投げているコミットで一通りレビューもらったら、差し替えていこうかなと思っていました！

2018-08-07 13:13 UTC, yuta-ushijima commented on app/controllers/api/users_controller.rb
> +    if @user.save
>validation に引っかかったら Error を返す save! を使うのが基本

ありがとうございます！今後意識していきます！

2018-08-07 13:17 UTC, yuta-ushijima commented on spec/controllers/api/users_controller_spec.rb
> +    let(:user) { FactoryBot.create(:user)}
>let(:user) { create(:user) }
で十分

この呼び出し方でもいけるんですね！ありがとうございます！

2018-08-07 13:18 UTC, yuta-ushijima commented on config/routes.rb
> +  namespace :api, { format: 'json'} do
どっちの方がいいんですかね。明示的にバージョンがわかる、`v1`切るのが基本でしょうか？

2018-08-07 13:26 UTC, mc-chinju commented on config/routes.rb
> +  namespace :api, { format: 'json'} do
実運用乗るサービスだったら `v1` 切ることが多いですが、まぁ今回はいらない気はしますね

2018-08-07 13:27 UTC, yuta-ushijima commented
> Rails 側で html 返す必要がないので不要

なるほど！ちょっと色々試してみます！

2018-08-07 14:20 UTC, yuta-ushijima commented
`webpack=vue`で用意されるファイル群を使う場合、railsのviewで読み込ませる必要があるっぽいです。

https://github.com/rails/webpacker#usage

今回のようにRails 側で html 返す必要がない場合、個別でディレクトリ作った方がいいっぽいので、それで一旦やってみます！

2018-08-07 15:49 UTC, yuta-ushijima commented on config/routes.rb
> +  namespace :api, { format: 'json'} do
コメントいただいているの見落としていたので、結局`v1`切りましたw

でも勉強になったので、これでいこうと思います！

2018-08-08 12:36 UTC, yuta-ushijima commented
色々と手直ししたので、またレビューいただけると嬉しいです！

2018-08-08 13:16 UTC, mc-chinju requested changes

2018-08-08 13:16 UTC, mc-chinju commented on spec/controllers/api/v1/users_controller_spec.rb
> +      user_params = FactoryBot.attributes_for(:user, first_name: "ジョブズ")
[Faker](https://github.com/stympy/faker/blob/master/doc/name.md) 使うとよりいいですよ。

```rb
user_params = attributes_for(
  :user,
  first_name: Faker::Name.first_name,
  last_name: Faker::Name.last_name,
)
```

みたいな感じです。
FactoryBot のデフォルトを変えれば、

```rb
user_params = attributes_for(:user)
```

だけでいいはず。

2018-08-08 13:16 UTC, mc-chinju commented on spec/factories/users.rb
> +    last_name "太郎"
これだと全員、「山田太郎」になってしまうので、

```
first_name: Faker::Name.first_name
last_name: Faker::Name.last_name
```

をデフォルトにしておくと、いろんな人ができて良さそうです。

2018-08-08 13:22 UTC, yuta-ushijima commented on spec/controllers/api/v1/users_controller_spec.rb
> +      user_params = FactoryBot.attributes_for(:user, first_name: "ジョブズ")
ありがとうございます！Fakerの使いどころへの理解が曖昧だったので、めちゃめちゃ勉強になります！

2018-08-08 13:23 UTC, yuta-ushijima commented on spec/factories/users.rb
> +    last_name "太郎"
FakerをFactoryBotで使う場合は、そのように実装するんですね！
ありがとうございます！

2018-08-08 13:27 UTC, mc-chinju approved these changes
local で rspec 走らせて通っていれば OK です！

2018-08-08 13:28 UTC, yuta-ushijima commented
>local で rspec 走らせて通っていれば OK です！

了解です！ALL GREENなのでマージしちゃいます！

2018-08-08 13:28 UTC, merged

2018-08-09 12:26 UTC, mc-chinju commented on spec/controllers/api/v1/users_controller_spec.rb
> +  end
```rb
  fdescribe "#update" do
    let(:user) { create(:user) }
    fit "ユーザー情報の更新ができること" do
      user_params = FactoryBot.attributes_for(:user)
      patch :update, params: { id: user.id, user: user_params}
      expect(user.reload.first_name).to eq(user.first_name)
    end
  end
```

```bash
$ bundle exec rspec --tag focus
```

2018-08-09 12:27 UTC, mc-chinju commented on spec/controllers/api/v1/users_controller_spec.rb
> +  end
```rb
fdescribe "#update" do, focus: true
```

と同じ。